Add a check that sudo works.
This only checks one specific sudo command (one that doesn't
require a specific path), but at least checks that the sudoers
file is installed. Because of the way we call sudo with -n, it
doesn't give a clear error message if it fails otherwise.

diff --git a/judge/chroot-startstop.sh.in b/judge/chroot-startstop.sh.in
--- a/judge/chroot-startstop.sh.in
+++ b/judge/chroot-startstop.sh.in
@@ -66,6 +66,16 @@ case "$1" in
 			>&2 echo "chroot dir '$CHROOTORIGINAL' incomplete, rerun dj_make_chroot"
 			exit 2
 		fi
+		# Check that sudo works
+		TMPDIR="$(mktemp -d)"
+		cd $TMPDIR
+		mkdir -p dev
+		if ! sudo -n cp -pR /dev/random /dev/urandom /dev/null dev < /dev/null || [ ! -e dev/null ]; then
+			>&2 echo "cannot run sudo successfully, check that sudoers file is installed"
+			rm -rf $TMPDIR
+			exit 2
+		fi
+		rm -rf $TMPDIR
 		;;
 	start)
 
