Remove duplicate code for cgroup/grub instruction

diff --git a/judge/create_cgroups.in b/judge/create_cgroups.in
--- a/judge/create_cgroups.in
+++ b/judge/create_cgroups.in
@@ -9,34 +9,31 @@
 JUDGEHOSTUSER=@DOMJUDGE_USER@
 CGROUPBASE=@judgehost_cgroupdir@
 
-for i in cpuset memory; do
-    mkdir -p $CGROUPBASE/$i
-    if [ ! -d $CGROUPBASE/$i/ ]; then
-        if ! mount -t cgroup -o$i $i $CGROUPBASE/$i/; then
-            echo "Error: Can not mount $i cgroup. Probably cgroup support is missing from running kernel. Unable to continue.
-
-            To fix this, please make the following changes:
-            1. In /etc/default/grub, add 'cgroup_enable=memory swapaccount=1' to GRUB_CMDLINE_LINUX_DEFAULT
-	       On modern distros (e.g. Debian bullseye and Ubuntu Jammy Jellyfish) which have cgroup v2 enabled by default,
-	       you need to add 'systemd.unified_cgroup_hierarchy=0' as well.
-            2. Run update-grub
-            3. Reboot" >&2
-            exit 1
-        fi
-    fi
-    mkdir -p $CGROUPBASE/$i/domjudge
-done
-
-if [ ! -f $CGROUPBASE/memory/memory.limit_in_bytes ] || [ ! -f $CGROUPBASE/memory/memory.memsw.limit_in_bytes ]; then
-    echo "Error: cgroup support missing memory features in running kernel. Unable to continue.
-
-    To fix this, please make the following changes:
+print_cgroup_instruction () {
+    echo ""
+    echo "To fix this, please make the following changes:
     1. In /etc/default/grub, add 'cgroup_enable=memory swapaccount=1' to GRUB_CMDLINE_LINUX_DEFAULT.
        On modern distros (e.g. Debian bullseye and Ubuntu Jammy Jellyfish) which have cgroup v2 enabled by default,
        you need to add 'systemd.unified_cgroup_hierarchy=0' as well.
     2. Run update-grub
     3. Reboot" >&2
     exit 1
+}
+
+for i in cpuset memory; do
+    mkdir -p $CGROUPBASE/$i
+    if [ ! -d $CGROUPBASE/$i/ ]; then
+        if ! mount -t cgroup -o$i $i $CGROUPBASE/$i/; then
+            echo "Error: Can not mount $i cgroup. Probably cgroup support is missing from running kernel. Unable to continue."
+            print_cgroup_instruction
+        fi
+    fi
+    mkdir -p $CGROUPBASE/$i/domjudge
+done
+
+if [ ! -f $CGROUPBASE/memory/memory.limit_in_bytes ] || [ ! -f $CGROUPBASE/memory/memory.memsw.limit_in_bytes ]; then
+    echo "Error: cgroup support missing memory features in running kernel. Unable to continue."
+    print_cgroup_instruction
 fi
 
 chown -R $JUDGEHOSTUSER $CGROUPBASE/*/domjudge
