Check if entry point is valid.
If it is not valid, we want to return a compile error rather than a run
time error.

diff --git a/sql/files/defaultdata/py2/run b/sql/files/defaultdata/py2/run
--- a/sql/files/defaultdata/py2/run
+++ b/sql/files/defaultdata/py2/run
@@ -22,6 +22,12 @@ EXITCODE=$?
 [ "$EXITCODE" -ne 0 ] && exit $EXITCODE
 rm -f -- *.pyc
 
+# Check if entry point is valid
+if [ ! -r "$MAINSOURCE" ]; then
+    >&2 echo "error: main source file '$MAINSOURCE' is not readable"
+    exit 1
+fi
+
 # Write executing script:
 cat > "$DEST" <<EOF
 #!/bin/sh
