Merge trunk to ipv6 branch.
git-svn-id: https://secure.a-eskwadraat.nl/svn/domjudge/branches/ipv6@1409 caf94f87-7bd6-0310-88dc-dee8202e2269

diff --git a/doc/team/Makefile b/doc/team/Makefile
--- a/doc/team/Makefile
+++ b/doc/team/Makefile
@@ -23,9 +23,13 @@ pdf: $(TARGETSPDF)
 
 $(TARGETSPDF): %.pdf: %.tex $(CONFIGDIR)/config.tex team-manual-preamble.tex \
                             ../examples/example.* ../logos/DOMjudgelogo.* $(LATEXPKGFILES)
-	-$(LATEX) $(LATEXFLAGS) $< < /dev/null &> /dev/null
-	-$(LATEX) $(LATEXFLAGS) $< < /dev/null &> /dev/null
-	 $(LATEX) $(LATEXFLAGS) $< < /dev/null
+	@NRUNS=3 ; echo -n "Running $$NRUNS passes of '$(LATEX) $(LATEXFLAGS) $<'..." ; \
+	 for ((i=1; i<=NRUNS; i++)) ; do \
+		if ! $(LATEX) $(LATEXFLAGS) $< </dev/null &>/dev/null ; then \
+			echo -e "\nTeX-ing failed in run $$i, see '$*.log' for details." ; \
+			exit 1 ; \
+		else echo -n " $$i" ; fi ; \
+	 done ; echo ;
 
 $(CONFIGDIR)/config.tex:
 	$(MAKE) -C $(CONFIGDIR) config.tex
