Add quiet option to gen_all_secrets script.
This allows running coverity submit scripts without
generating output.

diff --git a/etc/gen_all_secrets b/etc/gen_all_secrets
--- a/etc/gen_all_secrets
+++ b/etc/gen_all_secrets
@@ -6,16 +6,37 @@ create_pw_file()
 	FILE="$2"
 
 	if [ -f "$FILE" ]; then
-		echo "Password file '$FILE' already exists, leaving untouched."
+		[ -n "$QUIET" ] || echo "Password file '$FILE' already exists, leaving untouched."
 		return
 	fi
 
-	echo -n "Running '$SCRIPT'... "
+	[ -n "$QUIET" ] || echo -n "Running '$SCRIPT'... "
 	touch "$FILE"
 	chmod go= "$FILE"
 	$SCRIPT > "$FILE"
-	echo "file '$FILE' created."
+	[ -n "$QUIET" ] || echo "file '$FILE' created."
 }
+
+while getopts ':q' OPT ; do
+	case "$OPT" in
+		q)
+			QUIET=1
+			;;
+		:)
+			echo "Error: option '$OPTARG' requires an argument."
+			exit 1
+			;;
+		?)
+			echo "Error: unknown option '$OPTARG'."
+			exit 1
+			;;
+		*)
+			echo "Error: unknown error reading option '$OPT', value '$OPTARG'."
+			exit 1
+			;;
+	esac
+done
+shift $((OPTIND-1))
 
 create_pw_file ./gendbpasswords dbpasswords.secret
 create_pw_file ./genrestapicredentials restapi.secret
