Throw an error if no memory is left for the JVM to allocate a heap.
Closes #423.

diff --git a/sql/files/defaultdata/java_javac/run b/sql/files/defaultdata/java_javac/run
--- a/sql/files/defaultdata/java_javac/run
+++ b/sql/files/defaultdata/java_javac/run
@@ -25,6 +25,14 @@ MEMJVM=65536
 
 MEMRESERVED=$((MEMSTACK + MEMJVM))
 
+# Calculate Java program memlimit as MEMLIMIT - max. JVM memory usage:
+MEMLIMITJAVA=$((MEMLIMIT - MEMRESERVED))
+
+if [ $MEMLIMITJAVA -le 0 ]; then
+	echo "Error: total memory $MEMLIMIT KiB <= $MEMJVM + $MEMSTACK = $MEMRESERVED KiB reserved for JVM and stack leaves none for heap."
+	exit 1
+fi
+
 # Java needs filename to match main class:
 if [ -z "$ENTRY_POINT" ]; then
 	[ -n "$DEBUG" ] && echo "Info: no ENTRY_POINT provided, assuming 'Main'."
@@ -45,9 +53,6 @@ EXITCODE=$?
 javap "$MAINCLASS" > /dev/null
 EXITCODE=$?
 [ "$EXITCODE" -ne 0 ] && exit $EXITCODE
-
-# Calculate Java program memlimit as MEMLIMIT - max. JVM memory usage:
-MEMLIMITJAVA=$((MEMLIMIT - MEMRESERVED))
 
 # Write executing script:
 # Executes java byte-code interpreter with following options
diff --git a/sql/files/defaultdata/java_javac_detect/run b/sql/files/defaultdata/java_javac_detect/run
--- a/sql/files/defaultdata/java_javac_detect/run
+++ b/sql/files/defaultdata/java_javac_detect/run
@@ -29,6 +29,14 @@ MEMJVM=65536
 
 MEMRESERVED=$((MEMSTACK + MEMJVM))
 
+# Calculate Java program memlimit as MEMLIMIT - max. JVM memory usage:
+MEMLIMITJAVA=$((MEMLIMIT - MEMRESERVED))
+
+if [ $MEMLIMITJAVA -le 0 ]; then
+	echo "Error: total memory $MEMLIMIT KiB <= $MEMJVM + $MEMSTACK = $MEMRESERVED KiB reserved for JVM and stack leaves none for heap."
+	exit 1
+fi
+
 # Java needs filename to match main class:
 if [ -z "$ENTRY_POINT" ]; then
 	[ -n "$DEBUG" ] && echo "Debug: no ENTRY_POINT provided, trying to detect main class."
@@ -81,9 +89,6 @@ fi
 java -cp "$COMPILESCRIPTDIR" DetectMain "$(pwd)" $MAINCLASS > /dev/null
 EXITCODE=$?
 [ "$EXITCODE" -ne 0 ] && exit $EXITCODE
-
-# Calculate Java program memlimit as MEMLIMIT - max. JVM memory usage:
-MEMLIMITJAVA=$((MEMLIMIT - MEMRESERVED))
 
 # Write executing script:
 # Executes java byte-code interpreter with following options
