Move cgroups check from init script to create_cgroups.
Also check for both swapaccount and cgroup_enable=memory.
This makes it more complete and will be run also if you don't
use the init script.

diff --git a/misc-tools/create_cgroups.in b/misc-tools/create_cgroups.in
--- a/misc-tools/create_cgroups.in
+++ b/misc-tools/create_cgroups.in
@@ -9,6 +9,16 @@
 JUDGEHOSTUSER=@DOMJUDGE_USER@
 CGROUPBASE=@judgehost_cgroupdir@
 
+if ! grep -Eq 'cgroup_enable.+memory' /proc/cmdline || ! grep -Eq 'swapaccount.+1' /proc/cmdline; then
+        echo "Error: cgroup support missing from running kernel. Unable to continue.
+
+        To fix this, please make the following changes:
+        1. In /etc/default/grub, add 'cgroup_enable=memory swapaccount=1' to GRUB_CMDLINE_LINUX_DEFAULT
+        2. Run update-grub
+        3. Reboot" >&2
+        exit 1
+fi
+
 for i in cpuset memory; do
 	mkdir -p $CGROUPBASE/$i
 	mount -t cgroup -o$i $i $CGROUPBASE/$i/
