Install SQL upgrade script and check for existence when upgrading.
git-svn-id: https://secure.a-eskwadraat.nl/svn/domjudge/trunk@3240 caf94f87-7bd6-0310-88dc-dee8202e2269

diff --git a/sql/dj-setup-database.in b/sql/dj-setup-database.in
--- a/sql/dj-setup-database.in
+++ b/sql/dj-setup-database.in
@@ -201,6 +201,10 @@ upgrade)
 	TMPFILE=`mktemp /tmp/domjudge-sql.XXXXXX`
 	read_dbpasswords
 	for i in "$SQLDIR"/upgrade/* ; do
+		if [ ! -r "$i" ]; then
+			echo "Error: cannot read upgrade script '$i'."
+			exit 1
+		fi
 		# First find the line where the upgrade check is performed to
 		# filter possible error messages later.
 		UPGRADELINE=`grep -n '@UPGRADE-CHECK@' "$i" | cut -d : -f 1`
